version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10

  pylint:
    steps:
    - name: Install Python dependencies
      run: make install

    - name: Lint Python code with pylint
      run: make lint

  pytest:
    install:
      runtime-versions:
        python: 3.10

    - name: Install Python dependencies
      run: make install

    - name: Test Python code with pytest
      env:
        DEVELOPER_KEY: $DEVELOPER_KEY
      run: make test

  hadolint:
    - name: Dockerfile linting with hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile