version: 0.2

env:
  secrets-manager:
    DEVELOPER_KEY: youtube-comment-microservice/developer_key:DEVELOPER_KEY
phases:
  install:
    runtime-versions:
      python: 3.10
  pre_build:
    commands:
      - python3 -m venv ~/.youtube-comment-microservice && source ~/.youtube-comment-microservice/bin/activate
      - make install
      - sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 && sudo chmod +x /bin/hadolint
  build:
    commands:
      - source ~/.youtube-comment-microservice/bin/activate
      - make lint
      - make test
      - hadolint Dockerfile
  post_build:
    commands:
      - zip -r eb resources .streamlit app.py docker_requirements.txt Dockerfile
artifacts:
  files:
    - ./eb.zip
  discard-paths: yes