name: Dev CI

on:
  push:
    branches:
      - dev

jobs:
  lint_and_test:
    name: Pylint and pyest microservice
    uses: ./.github/workflows/job_lint_test_microservice.yml

  hadolint:
    name: Hadolint Dockerfile
    uses: ./.github/workflows/job_hadolint_dockerfile.yml

  build_and_push_img:
    name: Docker Build and Push
    needs: [lint_and_test, hadolint]
    uses: ./.github/workflows/job_build_push_img.yml