name: Build and Push to DockerHub

on:
  workflow_call:

jobs:
  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: stevenherrera/youtube-comment-microservice
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}