name: Pytest Microservice

on:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      DEVELOPER_KEY: ${{ secrets.DEVELOPER_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          make install
          make test