name: Dev CI 

on:
  push:
    branches:
      - dev
jobs:
  dependencies:
    - name: Dev Dependencies
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v4
      - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
      - name: Install dependencies
      run: |
        make install

  lint:
    - name: Dev Lint
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Lint with pylint
      run: |
        make lint

  test:
    - name: Dev Test
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Test with pytest
      env:
        DEVELOPER_KEY: ${{ secrets.DEVELOPER_KEY }}
      run: |
        make test

  hadolint:
    - name: Dev Dockerfile Lint
    uses: hadolint/hadolint-action@v3.1.0
    with:
      dockerfile: Dockerfile

  docker:
    - name: Dev Docker Build and Push
    needs: hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: stevenherrera/youtube-comment-microservice
        tags: v1, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}