name: GitHub Actions

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: make install

    - name: Lint Python code with pylint
      run: make lint

  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: make install

    - name: Test Python code with pytest
      env:
        DEVELOPER_KEY: ${{ secrets.DEVELOPER_KEY }}
      run: make test

  hadolint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Dockerfile linting with hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile

  build_and_push:
    runs-on: ubuntu-latest
    needs: [pylint, pytest, hadolint]
    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/youtube-comment-microservice:v3 , ${{secrets.DOCKER_USERNAME }}/youtube-comment-microservice:latest
