name: Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      env:
        DEVELOPER_KEY: ${{ secrets.DEVELOPER_KEY }}
      run: |
        make test

  - name: Dockerfile linting
    uses: hadolint/hadolint-action@v3.1.0
    with:
      dockerfile: Dockerfile
    # - name: Hadolint Dockerfile
      # run: |
      #   python3 -m venv venv
      #   . venv/bin/activate
      #   wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
      #   chmod +x /bin/hadolint
      #   hadolint Dockerfile